import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { LoaderProvider } from "@/contexts/loader";
import Menu from "@/components/menu/menu";
import LoaderInitializer from "@/components/loader/initializer";
import ClientLayout from "./client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <LoaderProvider>
          <LoaderInitializer />
          <header>
            <Menu />
          </header>
          <ClientLayout>{children}</ClientLayout>
        </LoaderProvider>
      </body>
    </html>
  );
}
